###
POST http://localhost:8080/api/andromeda/setting/addSettingToUser
Content-Type: application/json

{

}

###
DELETE http://localhost:8080/api/andromeda/setting/removeSettingOfUser/1/pathToPromtList
Content-Type: application/json

###
PUT http://localhost:8080/api/andromeda/setting/updateSettingOfUser
Content-Type: application/json

###
GET http://localhost:8080/api/andromeda/setting/getSettingsByUser/
###
GET http://localhost:8080/api/andromeda/setting/getSettingByUser/1/pathToPromtList
