###
POST http://localhost:8080/api/andromeda/setting/addSettingToUser
Content-Type: application/json

{

}

###
DELETE http://localhost:8080/api/andromeda/setting/removeSettingOfUser
Content-Type: application/json

{
  "id": 1
}

###
PUT http://localhost:8080/api/andromeda/setting/updateSettingOfUser
Content-Type: application/json

###
GET http://localhost:8080/api/andromeda/setting/getSettingsByUser/1

###
GET http://localhost:8080/api/andromeda/setting/getSettingByUser/1/pathToPromtList
