###
POST http://localhost:8080/api/andromeda/addUser
Content-Type: application/json

{
  "username": "Peter"
}

###
POST http://localhost:8080/api/andromeda/addPrompt
Content-Type: application/json

{
  "userId": 1,
  "content": "Verschiebe Datei (A) nach (B)"
}

###
POST http://localhost:8080/api/andromeda/addPrompt
Content-Type: application/json

{
  "userId": 1,
  "content": "Schalte den Rechner aus"
}

###
POST http://localhost:8080/api/andromeda/addPrompt
Content-Type: application/json

{
  "userId": 1,
  "content": "Öffne Programm (A)"
}

###
POST http://localhost:8080/api/andromeda/addPrompt
Content-Type: application/json

{
  "userId": 1,
  "content": "Schließe Programm (A)"
}

###
POST http://localhost:8080/api/andromeda/addPrompt
Content-Type: application/json

{
  "userId": 1,
  "content": "Führe ein git commit aus"
}

###
POST http://localhost:8080/api/andromeda/addPrompt
Content-Type: application/json

{
  "userId": 1,
  "content": "Spiel die Wiedergabe"
}

###
POST http://localhost:8080/api/andromeda/addPrompt
Content-Type: application/json

{
  "userId": 1,
  "content": "Pausiere die Wiedergabe"
}

###
POST http://localhost:8080/api/andromeda/addPrompt
Content-Type: application/json

{
  "userId": 1,
  "content": "Komprimiere Datei (A)"
}

###
POST http://localhost:8080/api/andromeda/addPrompt
Content-Type: application/json

{
  "userId": 1,
  "content": "Suche Datei (A)"
}

###
POST http://localhost:8080/api/andromeda/addPrompt
Content-Type: application/json

{
  "userId": 1,
  "content": "Geh in Verzeichnis (A)"
}

###
POST http://localhost:8080/api/andromeda/addPrompt
Content-Type: application/json

{
  "userId": 1,
  "content": "Schalte dich selbst aus"
}

###
GET http://localhost:8080/api/andromeda/prompts/listAll
Content-Type: */*