# docker-compose.yml
version: "3.8"
services:
  h2:
    image: oscarfonts/h2
    ports:
      - "1521:1521"   # JDBC port
      - "81:81"       # Web Console (optional)
    environment:
      - H2_OPTIONS=-ifNotExists
