name: Backend Request testing

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16-alpine
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: demo
          POSTGRES_PASSWORD: demo
          POSTGRES_DB: demo
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set executable permission for mvnw
        run: chmod +x mvnw

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Wait for Postgres to be ready
        run: |
          until pg_isready -h localhost -p 5432 -U demo; do
            echo "Waiting for Postgres..."
            sleep 2
          done
        env:
          PGPASSWORD: demo

      - name: Build and test with Maven
        run: ./mvnw clean verify
